### ISSUE TITLE
Use ionic state restore command to restore platform and plugins

### ISSUE THREAD

**Issue by ygayl** [arun0009/ionicapp#1]
Hi @arun0009 ,

The ionic-clean-build task defined in the gulpfile can be updated with the new feature of Ionic CLI : ionic state restore.

Please fin more informations here: https://github.com/arun0009/ionicapp/issues/new

Best,
Yassine

**Comment by arun0009** [comment]
@ygayl - Thanks for your suggestions. I have made changes to package.json with appropriate plugins & platforms and updated read me file to use ionic state restore instead of custom gulp ionic-clean-build.

I will close this issue unless you have additional comments.
